# Generated by Django 4.2.6 on 2023-10-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(max_length=255)),
                ('esito', models.CharField(max_length=255)),
                ('struttura', models.CharField(default='PROVA', max_length=255)),
                ('file_referto', models.FileField(null=True, upload_to='')),
                ('cda2', models.TextField(null=True)),
            ],
        ),
    ]
